function mainFigue()

global pathOfProgram

addpath(genpath(pwd));
pathOfProgram = pwd;

%% Graficke objekty figure a nadpisy
Monitor = get(0,'ScreenSize');                  % Rozliseni obrazovky monitoru
      	
h = figure('Units','Pixels','Name','Animal EEG analyzator',...
    'Position',[0.01*Monitor(3) 0.01*Monitor(4) 0.9*Monitor(3) 0.8*Monitor(4)],...
    'Tag','currentFigure','Color',[1 1 1],...
    'NumberTitle','off','Resize','on','MenuBar','None','handlevisib','on');

set(groot,'CurrentFigure',h);


%% Panel - Absolute power (frequency bands)
uicontrol('Style','Push','String','Absolute power (frequency bands)','FontSize',18,... 
    'tag','AbsolutePower',...
    'BackgroundColor',[1.000 0.200 0.200],...
    'Units','Normalized','Position',[0.02 .55 .3 .3],... 
    'Callback','absolutePowerFrequencyBandsTesting;');

%% Panel - Absolute power (1Hz step)
uicontrol('Style','Push','String','Absolute power (1Hz step)','FontSize',18,... 
    'tag','AbsolutePower1Hz',...
    'BackgroundColor',[0.800 0.000 0.000],...
    'Units','Normalized','Position',[0.02 .15 .3 .3],... 
    'Callback','absolutePower1HzTesting');


%% Panel - Relativee power (frequency bands)
uicontrol('Style','Push','String','Relative power (frequency bands)','FontSize',18,... 
    'tag','RelativePower',...
    'BackgroundColor',[0.400 0.800 0.200],...
    'Units','Normalized','Position',[0.34 0.55  .3 .3],... 
    'Callback','relativePowerTesting;');

%% Panel - Relative power (1Hz step)
uicontrol('Style','Push','String','Relative power (1Hz step)','FontSize',18,... 
    'tag','RelativePower1Hz',...
    'BackgroundColor',[0.298 0.600 0.000],...
    'Units','Normalized','Position',[0.34 0.15  .3 .3],...
    'Callback','relativePowerTesting1Hz;');
            
%% Panel - Coherence            
uicontrol('Style','Push','String','Coherence','FontSize',18,... 
    'tag','Coherence',...
    'BackgroundColor',[0.000 0.749 1.000],...
    'Units','Normalized','Position',[0.66 .55 .3 .3],...
    'Callback','coherenceTesting;');

%% Panel - Phase Lag
uicontrol('Style','Push','String','Phase Lag','FontSize',18,... 
    'tag','PhaseLag',...
    'BackgroundColor',[0.000 0.298 0.600],...
    'Units','Normalized','Position',[0.66 .15 .3 .3],... 
    'Callback','phaseLagTesting;');

end